# Some important Numpy functions

In [1]:
import numpy as np

In [7]:
np.random.random()

0.05952449697569773

In [10]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [13]:
np.random.uniform(3,11)

5.418660581054718

In [ ]:
np.random.uniform(1,100,10)
# np.random.uniform(1,100,10).reshape(2,5)

array([[69.49583428, 32.23604747, 68.96359184, 83.62794152,  2.81053946],
       [75.26428718, 98.8972478 , 75.06839978, 28.76395521, 79.13865352]])

In [17]:
np.random.randint(1,10,5)

array([9, 7, 4, 8, 8], dtype=int32)

In [19]:
np.random.randint(1,10,15).reshape(3,5)

array([[2, 2, 4, 1, 9],
       [7, 5, 6, 7, 3],
       [6, 8, 9, 5, 5]], dtype=int32)

In [21]:
a = np.random.randint(1,10,6)
a

array([8, 8, 5, 1, 3, 1], dtype=int32)

In [22]:
np.max(a)

np.int32(8)

In [23]:
np.min(a)

np.int32(1)

In [28]:
np.argmax(a)

np.int64(0)

In [25]:
a[np.argmax(a)]

np.int32(8)

In [26]:
a[np.argmin(a)]

np.int32(1)

In [27]:
np.argmin(a)

np.int64(3)

In [39]:
a=np.random.randint(1,10,6)
a

array([6, 2, 3, 2, 6, 5], dtype=int32)

In [40]:
a[a%2 == 1] = -1
a

array([ 6,  2, -1,  2,  6, -1], dtype=int32)

In [43]:
# where(condition,True,false)

In [45]:
a = np.random.randint(1,50,6)
a

array([ 7, 14, 16, 25, 10,  3], dtype=int32)

In [46]:
np.where(a%2 == 1 , -1 , a )

array([-1, 14, 16, -1, 10, -1], dtype=int32)

In [47]:
out = np.where(a%2==1 , -1 , a)
out

array([-1, 14, 16, -1, 10, -1], dtype=int32)

In [55]:
a = np.random.randint(1,50,10)
a

array([41, 15, 46, 24, 17, 29, 43, 46,  4,  3], dtype=int32)

In [56]:
b = np.sort(a)
b

array([ 3,  4, 15, 17, 24, 29, 41, 43, 46, 46], dtype=int32)

In [57]:
np.percentile(a,25)

np.float64(15.5)

In [58]:
np.percentile(a,50)

np.float64(26.5)

In [59]:
np.percentile(a,99.8)

np.float64(46.0)