# creating numpy/ n-d arrays

In [ ]:
import numpy as np


hello


In [5]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
arr5= np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
arr6 = np.arange(10)
# arr6 = np.arange(5,6)
# arr6 = np.arange(1,15,2)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# linspace  --  np.linspace(initial_value , end_value , Gap_value )
# arr7= np.linspace(10,20,10)
arr7 = np.linspace(5,10,2)
arr7

array([ 5., 10.])

In [30]:
arr8 = arr7.copy()
arr8

array([ 5., 10.])