# Properties & Attributes

1. Shape
2. nDim
3. Size
4. Itemsize
5. Dtype
6. astype()

In [2]:
import numpy as np

In [14]:
arr1 = np.array([1,2,3,4,5])
print(arr1)


[1 2 3 4 5]


In [15]:
arr2 = np.array([[1,1,1,1],[2,2,2,2]])
arr2


array([[1, 1, 1, 1],
       [2, 2, 2, 2]])

In [45]:
arr3 = np.array([[[1,2,3]],[[2,3,4]],[[3,4,5]]])
arr3

array([[[1, 2, 3]],

       [[2, 3, 4]],

       [[3, 4, 5]]])

In [34]:
arr4 = np.zeros((2,3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
arr5 = np.ones((3,3))
arr5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# To find the shape of the array 

In [23]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(5,)
(2, 4)
(1, 3, 3)


In [17]:
arr2.shape

(2, 4)

In [19]:
arr3.shape

(1, 3, 3)

# To find the dimension of array

In [25]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


# To find the size of array

In [26]:
arr1.size

5

In [27]:
arr2.size

8

In [28]:
arr3.size

9

In [36]:
arr4.size

6

# Difference between size and itemsize 
1. size → Total number of elements

It tells you how many elements are present in the array.

2. itemsize → Memory occupied by each element

It tells you how many bytes one element occupies.

# To find the itemsize of the array

In [44]:
arr4.itemsize

8

In [46]:
arr3.itemsize

8

# To find the datatype of an array


In [47]:
arr2.dtype

dtype('int64')

In [48]:
arr4.dtype

dtype('float64')

# To change  the type of an array

In [51]:
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
arr4.astype('int')

array([[0, 0, 0],
       [0, 0, 0]])

In [52]:
arr3

array([[[1, 2, 3]],

       [[2, 3, 4]],

       [[3, 4, 5]]])

In [53]:
arr3.astype('float')

array([[[1., 2., 3.]],

       [[2., 3., 4.]],

       [[3., 4., 5.]]])