# Iteration
Iteration means visiting each element of a NumPy array one by one using a loop.

# Indexing
Indexing means accessing a specific element from a NumPy array using its position (index).


# Slicing
Slicing means extracting a part/range of elements from a NumPy array.

# Reshaping an Numpy array

In [2]:
import numpy as np

In [4]:
array_a = np.arange(24)
array_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [8]:
array_a.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Indexing of an array OR extracting elements using the index 

# For 1-D array

In [9]:
array_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
arr = array_a.copy()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [17]:
print(arr[14])
arr[14]

14


np.int64(14)

In [19]:
print(arr[2:6])
arr[2:6]

[2 3 4 5]


array([2, 3, 4, 5])

In [21]:
print(arr[2:10:2])
arr[2:10:2]

[2 4 6 8]


array([2, 4, 6, 8])

# For 2-D array

In [24]:
arr1 = np.array([[1,2,3],[2,3,4],[3,4,5]])
arr1

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [28]:
print(arr1[2])
arr1[2]

[3 4 5]


array([3, 4, 5])

In [30]:
# suppose we only extract the 2nd element of every array from the arr1
print(arr1[:,1])
arr1[:,1]

[2 3 4]


array([2, 3, 4])

In [38]:
print(arr1[:,0:2])
arr1[:,1:3]

[[1 2]
 [2 3]
 [3 4]]


array([[2, 3],
       [3, 4],
       [4, 5]])

# Iteration


In [40]:
for i in arr1:
    print (i)

[1 2 3]
[2 3 4]
[3 4 5]


In [41]:
for i in np.nditer(arr1):
    print(i)

1
2
3
2
3
4
3
4
5
