# Reshaping Numpy Array

1. Ravel    -- it basically convert n-d arrays into 1-d arrayx
2. Reshape
3. Transpose
4. Stacking
5. Splitting

In [1]:
import numpy as np

In [ ]:
arr1= np.array[[1,2,3],[3,4,5],[4,5,6]]
arr1

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [8]:
arr1.shape

(3, 3)

# Ravel

In [13]:
arr1.ravel()

array([1, 2, 3, 3, 4, 5, 4, 5, 6])

# Transpose

In [15]:
arr1.transpose()

array([[1, 3, 4],
       [2, 4, 5],
       [3, 5, 6]])

# Stacking

In [20]:
arr2 = np.ones((3,3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# hstack -- horizontal stack
np.hstack((arr1,arr2))

array([[1., 2., 3., 1., 1., 1.],
       [3., 4., 5., 1., 1., 1.],
       [4., 5., 6., 1., 1., 1.]])

In [23]:
# vstack -- vertical stack
np.vstack((arr1,arr2))

array([[1., 2., 3.],
       [3., 4., 5.],
       [4., 5., 6.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Splitting

In [ ]:
# hsplit  -- horizontal split
np.hsplit(arr1,3)

[array([[1],
        [3],
        [4]]),
 array([[2],
        [4],
        [5]]),
 array([[3],
        [5],
        [6]])]

In [25]:
#  vsplit  -- vertical split
np.vsplit(arr1,3)

[array([[1, 2, 3]]), array([[3, 4, 5]]), array([[4, 5, 6]])]