# Numpy Features

In [1]:
import numpy as np

In [5]:
arr1 = np.arange(24).reshape(6,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
#  fancy indexing 

#  it will extract the rows what we want



In [7]:
arr1[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [ ]:
arr1[[0,4,2]]       # (start,step,stop)

array([[ 0,  1,  2,  3],
       [16, 17, 18, 19],
       [ 8,  9, 10, 11]])